<script lang="ts">
	import { api } from '$lib/api';
	interface Room { id: string; name: string; ownerId: string | null; visibility: string; memberCount: number; participantCount: number; }
	let rooms = $state<Room[]>([]); let nextOffset = $state<number | null>(null); let loading = $state(false); let error = $state(''); let notice = $state(''); let takeover = $state<Room | null>(null); let reason = $state('');
	async function load(offset = 0, append = false) { loading = true; try { const result = await api<{ rooms: Room[]; nextOffset: number | null }>(`/api/admin/rooms?limit=25&offset=${offset}`); rooms = append ? [...rooms, ...result.rooms] : result.rooms; nextOffset = result.nextOffset; } catch (cause) { error = cause instanceof Error ? cause.message : 'Unable to load rooms'; } finally { loading = false; } }
	$effect(() => { load(); });
	async function confirmTakeover() { if (!takeover || reason.trim().length < 3) return; if (!confirm(`Take ownership of ${takeover.name}? The current owner will become a moderator.`)) return; loading = true; error = ''; try { await api(`/api/admin/rooms/${takeover.id}/takeover`, { method: 'POST', body: { reason: reason.trim() } }); notice = `You now own ${takeover.name}.`; takeover = null; reason = ''; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : 'Takeover failed'; } finally { loading = false; } }
</script>
<div><h2 class="text-2xl">Rooms</h2><p class="mb-5 mt-1 text-sm text-text-secondary">Inspect rooms and perform audited emergency ownership takeover.</p>{#if error}<p class="mb-3 text-sm text-lag-danger">{error}</p>{/if}{#if notice}<p class="mb-3 text-sm text-lag-success">{notice}</p>{/if}<div class="space-y-3">{#each rooms as room (room.id)}<article class="flex flex-wrap items-center gap-3 rounded-lg border border-border bg-surface p-4"><div class="min-w-48 flex-1"><h3>{room.name}</h3><p class="text-xs text-text-muted">{room.visibility} · {room.memberCount} members · {room.participantCount} active</p><p class="mt-1 break-all text-xs text-text-muted">Owner: {room.ownerId ?? 'none'}</p></div><button onclick={() => { takeover = room; reason = ''; }} class="rounded border border-lag-warning/50 px-3 py-1.5 text-xs text-lag-warning">Take over</button></article>{/each}</div>{#if nextOffset !== null}<button onclick={() => load(nextOffset ?? 0, true)} class="mt-4 w-full rounded-lg border border-border py-2 text-sm">Load more</button>{/if}</div>
{#if takeover}<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-3" role="presentation" onclick={(event) => event.target === event.currentTarget && (takeover = null)}><form onsubmit={(event) => { event.preventDefault(); confirmTakeover(); }} class="w-full max-w-md rounded-lg border border-border bg-surface-elevated p-5"><h3 class="text-lg">Take over {takeover.name}</h3><p class="my-2 text-sm text-text-secondary">A reason is required and recorded in the audit log.</p><textarea bind:value={reason} minlength="3" maxlength="1000" required rows="4" class="w-full rounded-lg border border-border bg-surface p-3 text-sm" placeholder="Operational reason"></textarea><div class="mt-4 flex justify-end gap-2"><button type="button" onclick={() => takeover = null} class="px-3 py-2 text-sm">Cancel</button><button disabled={loading || reason.trim().length < 3} class="rounded-lg bg-lag-danger px-3 py-2 text-sm text-white disabled:opacity-50">Confirm takeover</button></div></form></div>{/if}
