<script lang="ts">
	import { api } from '$lib/api';
	interface Event { id: string; action: string; actorUserId: string | null; targetType: string; targetId: string | null; createdAt: string; metadata: unknown; clientIp: string | null; }
	let events = $state<Event[]>([]); let nextCursor = $state<string | null>(null); let action = $state(''); let actorUserId = $state(''); let targetType = $state(''); let targetId = $state(''); let before = $state(''); let loading = $state(false); let error = $state('');
	function params(cursor?: string) { const value = new URLSearchParams({ limit: '25' }); for (const [key, item] of Object.entries({ action, actorUserId, targetType, targetId, before })) if (item.trim()) value.set(key, item.trim()); if (cursor) { value.set('cursor', cursor); value.delete('before'); } return value; }
	async function load(cursor?: string, append = false) { loading = true; error = ''; try { const result = await api<{ events: Event[]; nextCursor: string | null }>(`/api/admin/audit?${params(cursor)}`); events = append ? [...events, ...result.events] : result.events; nextCursor = result.nextCursor; } catch (cause) { error = cause instanceof Error ? cause.message : 'Unable to load audit events'; } finally { loading = false; } }
	$effect(() => { load(); });
</script>
<div><h2 class="text-2xl">Audit log</h2><p class="mb-5 mt-1 text-sm text-text-secondary">Filter and page through recorded administrative activity.</p><form onsubmit={(event) => { event.preventDefault(); load(); }} class="mb-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3"><input bind:value={action} placeholder="Exact action" class="rounded-lg border border-border bg-surface px-3 py-2 text-sm" /><input bind:value={actorUserId} placeholder="Actor user ID" class="rounded-lg border border-border bg-surface px-3 py-2 text-sm" /><input bind:value={targetType} placeholder="Target type" class="rounded-lg border border-border bg-surface px-3 py-2 text-sm" /><input bind:value={targetId} placeholder="Target ID" class="rounded-lg border border-border bg-surface px-3 py-2 text-sm" /><label class="flex items-center gap-2 rounded-lg border border-border bg-surface px-3 text-xs text-text-muted">Before<input bind:value={before} type="datetime-local" class="min-w-0 flex-1 bg-transparent py-2 text-sm text-foreground" /></label><button class="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">Apply filters</button></form>{#if error}<p class="mb-3 text-sm text-lag-danger">{error}</p>{/if}<div class="space-y-2">{#each events as event (event.id)}<article class="rounded-lg border border-border bg-surface p-3"><div class="flex flex-wrap justify-between gap-2"><strong class="text-sm">{event.action}</strong><time class="text-xs text-text-muted">{new Date(event.createdAt).toLocaleString()}</time></div><p class="mt-1 break-all text-xs text-text-secondary">Actor {event.actorUserId ?? 'system'} → {event.targetType}:{event.targetId ?? '-'}</p><p class="mt-1 break-all font-mono text-[11px] text-text-muted">{JSON.stringify(event.metadata)}</p></article>{/each}</div>{#if !events.length && !loading}<p class="rounded-lg bg-surface p-5 text-text-muted">No matching events.</p>{/if}{#if nextCursor}<button disabled={loading} onclick={() => load(nextCursor ?? undefined, true)} class="mt-4 w-full rounded-lg border border-border py-2 text-sm disabled:opacity-50">{loading ? 'Loading...' : 'Load older events'}</button>{/if}</div>
