<script lang="ts">
	import { getSessionState, isPlatformAdmin } from '$lib/stores/session.svelte';
	import { createRoomInviteLink, fetchRoomMembers, inviteRoomUser, removeMember, searchRoomUsers, transferRoomOwnership, unbanRoomUser, updateMemberRole, updateRoomSettings, type Room, type RoomMember, type RoomRole, type RoomUserSearchResult } from '$lib/stores/rooms.svelte';

	let { room, onclose, onupdated }: { room: Room; onclose: () => void; onupdated: (room: Room) => void } = $props();
	const session = $derived(getSessionState());
	let tab = $state<'settings' | 'members' | 'invites' | 'bans'>('settings'); let members = $state<RoomMember[]>([]); let loading = $state(false); let error = $state(''); let notice = $state(''); let saved = $state(false);
	let name = $state(''); let maxParticipants = $state(50); let visibility = $state<Room['visibility']>('public'); let allowGuests = $state(true); let defaultRole = $state<Room['defaultRole']>('listener'); let historyVisibility = $state<Room['historyVisibility']>('all'); let retention = $state<Room['retention']>('30');
	let search = $state(''); let results = $state<RoomUserSearchResult[]>([]); let inviteRole = $state<Exclude<RoomRole, 'owner'>>('listener'); let expiresInHours = $state(24); let maxUses = $state(1); let inviteUrl = $state(''); let unbanUserId = $state('');
	let initialized = false;
	$effect(() => { if (!initialized) { name = room.name; maxParticipants = room.maxParticipants; visibility = room.visibility; allowGuests = room.allowGuests; defaultRole = room.defaultRole; historyVisibility = room.historyVisibility; retention = room.retention; initialized = true; } });
	const canModerate = $derived(isPlatformAdmin(session.user) || room.role === 'owner' || room.role === 'moderator');
	const canTransfer = $derived(room.role === 'owner' || isPlatformAdmin(session.user));
	async function loadMembers() { if (members.length || loading) return; loading = true; try { members = await fetchRoomMembers(room.id); } catch (cause) { fail(cause, 'Unable to load members'); } finally { loading = false; } }
	function fail(cause: unknown, fallback: string) { error = cause instanceof Error ? cause.message : fallback; }
	async function save() { loading = true; error = ''; saved = false; try { const updated = await updateRoomSettings(room.id, { name, maxParticipants, visibility, allowGuests, defaultRole, historyVisibility, retention }); onupdated({ ...room, ...updated }); saved = true; } catch (cause) { fail(cause, 'Unable to save settings'); } finally { loading = false; } }
	async function changeRole(member: RoomMember, role: Exclude<RoomRole, 'owner'>) { error = ''; try { await updateMemberRole(room.id, member.userId, role); member.role = role; members = [...members]; } catch (cause) { fail(cause, 'Unable to update member'); } }
	async function remove(member: RoomMember, action: 'kick' | 'ban') { if (!confirm(`${action === 'ban' ? 'Ban' : 'Remove'} ${member.nickname} from this room?`)) return; error = ''; try { await removeMember(room.id, member.userId, action); members = members.filter((item) => item.userId !== member.userId); notice = `${member.nickname} ${action === 'ban' ? 'banned' : 'removed'}.`; } catch (cause) { fail(cause, 'Unable to remove member'); } }
	async function findUsers() { if (search.trim().length < 2) return; loading = true; error = ''; try { results = await searchRoomUsers(room.id, search.trim()); } catch (cause) { fail(cause, 'Unable to search users'); } finally { loading = false; } }
	async function invite(user: RoomUserSearchResult) { error = ''; try { await inviteRoomUser(room.id, user.id, inviteRole, expiresInHours); notice = `Invitation sent to ${user.nickname}.`; } catch (cause) { fail(cause, 'Unable to invite user'); } }
	async function makeLink() { error = ''; inviteUrl = ''; try { const invitation = await createRoomInviteLink(room.id, inviteRole, expiresInHours, maxUses); inviteUrl = `${location.origin}/rooms?invitation=${encodeURIComponent(invitation.token ?? '')}`; notice = 'Invite link created. It is only shown now.'; } catch (cause) { fail(cause, 'Unable to create invite link'); } }
	async function transfer(member: RoomMember) { if (!confirm(`Request ownership transfer to ${member.nickname}? They must confirm within 24 hours.`)) return; try { await transferRoomOwnership(room.id, member.userId); notice = `Ownership transfer requested for ${member.nickname}.`; } catch (cause) { fail(cause, 'Unable to request transfer'); } }
	async function unban() { const id = unbanUserId.trim(); if (!id || !confirm(`Remove the room ban for user ${id}?`)) return; try { await unbanRoomUser(room.id, id); notice = `Ban removed for ${id}.`; unbanUserId = ''; } catch (cause) { fail(cause, 'Unable to remove ban'); } }
</script>

<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-3" role="presentation" onclick={(event) => event.target === event.currentTarget && onclose()}><div class="flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-lg border border-border bg-surface-elevated shadow-lg"><header class="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 class="text-lg">Manage {room.name}</h2><p class="text-xs text-text-muted">{room.role ?? 'visitor'} access</p></div><button onclick={onclose} class="text-sm text-text-muted">Close</button></header>
	<div class="flex overflow-x-auto border-b border-border px-3">{#each ['settings', 'members', 'invites', 'bans'] as value}<button onclick={() => { tab = value as typeof tab; if (value === 'members') loadMembers(); }} class="whitespace-nowrap px-3 py-2 text-sm {tab === value ? 'border-b-2 border-primary text-foreground' : 'text-text-muted'}">{value[0].toUpperCase() + value.slice(1)}</button>{/each}</div>
	<div class="overflow-y-auto p-5">{#if tab === 'settings'}<div class="grid gap-4 sm:grid-cols-2"><label class="text-sm text-text-secondary sm:col-span-2">Name<input bind:value={name} maxlength="64" class="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2" /></label><label class="text-sm text-text-secondary">Visibility<select bind:value={visibility} class="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2"><option value="public">Public</option><option value="unlisted">Unlisted</option><option value="private">Private</option></select></label><label class="text-sm text-text-secondary">Default role<select bind:value={defaultRole} class="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2"><option value="listener">Listener</option><option value="speaker">Speaker</option></select></label><label class="text-sm text-text-secondary">History<select bind:value={historyVisibility} class="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2"><option value="all">All</option><option value="since_membership">Since membership</option><option value="none">None</option></select></label><label class="text-sm text-text-secondary">Retention<select bind:value={retention} class="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2"><option value="7">7 days</option><option value="30">30 days</option><option value="forever">Forever</option></select></label><label class="text-sm text-text-secondary">Capacity<input type="number" min="1" max="100" bind:value={maxParticipants} class="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2" /></label><label class="flex items-center gap-2 self-end py-2 text-sm"><input type="checkbox" bind:checked={allowGuests} /> Allow guests</label></div><div class="mt-5 flex justify-end gap-3">{#if saved}<span class="text-sm text-lag-success">Saved</span>{/if}<button onclick={save} disabled={loading} class="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">Save settings</button></div>
	{:else if tab === 'members'}{#if loading}<p>Loading...</p>{:else}<div class="space-y-2">{#each members as member (member.userId)}<div class="flex flex-wrap items-center gap-2 rounded-lg bg-surface p-3"><span class="h-7 w-7 rounded-full" style:background-color={member.avatarColor}></span><span class="min-w-28 flex-1 text-sm">{member.nickname}</span><span class="text-xs text-text-muted">{member.role}</span>{#if canModerate && member.role !== 'owner' && member.userId !== session.user?.id}<select value={member.role} onchange={(event) => changeRole(member, event.currentTarget.value as Exclude<RoomRole, 'owner'>)} class="rounded border border-border bg-surface-elevated px-2 py-1 text-xs"><option value="moderator">Moderator</option><option value="speaker">Speaker</option><option value="listener">Listener</option></select>{#if canTransfer}<button onclick={() => transfer(member)} class="text-xs text-primary">Transfer ownership</button>{/if}<button onclick={() => remove(member, 'kick')} class="text-xs text-lag-warning">Kick</button><button onclick={() => remove(member, 'ban')} class="text-xs text-lag-danger">Ban</button>{/if}</div>{/each}</div>{/if}
	{:else if tab === 'invites'}<div class="space-y-5"><div class="grid gap-3 sm:grid-cols-3"><label class="text-sm">Role<select bind:value={inviteRole} class="mt-1 w-full rounded border border-border bg-surface p-2"><option value="listener">Listener</option><option value="speaker">Speaker</option>{#if canTransfer}<option value="moderator">Moderator</option>{/if}</select></label><label class="text-sm">Expires (hours)<input bind:value={expiresInHours} type="number" min="1" max="720" class="mt-1 w-full rounded border border-border bg-surface p-2" /></label><label class="text-sm">Link uses<input bind:value={maxUses} type="number" min="1" max="1000" class="mt-1 w-full rounded border border-border bg-surface p-2" /></label></div><div><h3 class="text-sm font-medium">Invite an OAuth user</h3><form onsubmit={(event) => { event.preventDefault(); findUsers(); }} class="mt-2 flex gap-2"><input bind:value={search} minlength="2" placeholder="Search nickname or exact email" class="min-w-0 flex-1 rounded border border-border bg-surface px-3 py-2 text-sm" /><button class="rounded bg-primary px-3 text-sm text-primary-foreground">Search</button></form><div class="mt-2 space-y-2">{#each results as user (user.id)}<div class="flex items-center rounded bg-surface p-2"><span class="flex-1 text-sm">{user.nickname}</span><button onclick={() => invite(user)} class="text-sm text-primary">Send invite</button></div>{/each}</div></div><div><button onclick={makeLink} class="rounded border border-border px-3 py-2 text-sm">Create invite link</button>{#if inviteUrl}<div class="mt-2 flex gap-2"><input readonly value={inviteUrl} class="min-w-0 flex-1 rounded border border-border bg-surface p-2 text-xs" /><button onclick={() => navigator.clipboard.writeText(inviteUrl)} class="rounded bg-primary px-3 text-xs text-primary-foreground">Copy</button></div>{/if}</div></div>
	{:else}<div class="rounded-lg border border-border bg-surface p-4"><h3>Unban by user ID</h3><p class="my-2 text-sm text-text-muted">The API supports unban but has no endpoint to list current bans.</p><form onsubmit={(event) => { event.preventDefault(); unban(); }} class="flex gap-2"><input bind:value={unbanUserId} required placeholder="User UUID" class="min-w-0 flex-1 rounded border border-border bg-surface-elevated px-3 py-2 text-sm" /><button class="rounded bg-primary px-3 text-sm text-primary-foreground">Unban</button></form></div>{/if}
	{#if error}<p class="mt-3 rounded bg-lag-danger-dim p-2 text-sm text-lag-danger">{error}</p>{/if}{#if notice}<p class="mt-3 text-sm text-lag-success">{notice}</p>{/if}</div></div></div>
